name: Auto Create PR

on:
  push:
    branches:
      - '*' # Trigger on any branch push
  pull_request:
    branches:
      - main # Trigger when a PR is created targeting the main branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "Auto-created PR for branch ${{ github.ref_name }}"
          body: |
            This Pull Request was automatically created for the branch: `${{ github.ref_name }}`.
          always-create: true
