name: Auto Create PR

on:
  push:
    branches:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create the Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # The branch you want to merge into
          head: ${{ github.ref_name }}  # The branch that triggered the push
          title: "Auto-created PR for branch ${{ github.ref_name }}"
          body: |
            This Pull Request was automatically created for the branch: `${{ github.ref_name }}`.

      # Step 3: Output the PR URL
      - name: Output Pull Request URL
        run: echo "PR URL: ${{ steps.create-pull-request.outputs.pull-request-url }}"
