name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install asdf and dependencies
      - name: Install asdf and plugins
        uses: asdf-vm/actions/install@v3
        with:
          asdf-version: v0.12.0
          plugins: |
            nodejs https://github.com/asdf-vm/asdf-nodejs.git
            yarn https://github.com/twuni/asdf-yarn.git
            java https://github.com/halcyon/asdf-java.git
        env:
          ASDF_NO_CHECK_FOR_UPDATES: "true"

      # Step 3: Install plugin versions from .tool-versions
      - name: Install plugin versions
        run: asdf install

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Run tests
      - name: Run tests
        run: yarn test --watch=false

      # Step 6: Run linting
      - name: Run lint
        run: yarn lint
